const path = require('path');

//it's not needed with contentful, slugs are generated by CMS
/* module.exports.onCreateNode = ({ node, actions }) => {
    const { createNodeField } = actions

    if(node.internal.type === "MarkdownRemark") {
        const slug = path.basename(node.fileAbsolutePath, '.md');
        createNodeField({
            node,
            name: 'slug',
            value: slug
        });
    }
} */

module.exports.createPages = async({ graphql, actions }) => {
    const { createPage } = actions;
    const blogTemplate = path.resolve('./src/templates/blogTemp.js');
    const res = await graphql(`
        query {
            allContentfulBlogPost {
                edges {
                  node {
                    slug
                  }
                }
              }
        }
    `);

    res.data.allContentfulBlogPost.edges.forEach(el => {
        createPage({
            component: blogTemplate,
            path: `/blog/${el.node.slug}`,
            context: {
                slug: el.node.slug
            }
        });
    });
}